### ISSUE TITLE
STAN- May Help, Not Sure

### ISSUE THREAD

**Issue by Jspecker7** [ICJIA/r-user-group#12]
I am not sure if this applies to any of us, but i found some new stuff about STAN in RStudio.    Thought I would flag it for everyone in case it would be helpful for anyone.  

https://blog.rstudio.com/2018/10/16/rstudio-1-2-preview-stan/

**Comment by bobaekang** [comment]
@Jspecker7 Thank you for sharing it!

This will definitely make it easier to fit various Bayesian models using [Stan](http://mc-stan.org/). I don't really have much experience in Stan yet, but if you do, you are more than welcome to share your experience here!
