### ISSUE TITLE
Sharing your ggplot2 examples

### ISSUE THREAD

**Issue by bobaekang** [ICJIA/r-user-group#20]
## Summary
Add a comment to this post with your own `ggplot2` example.

## Main
Share your own ggplot2 example by commenting on this post.

We'll be reviewing the shared plots at the February meeting. This exercise will help us to learn from one another useful tips and tricks in crafting `ggplot2` visualizations and to think critically about how to improve your own work.

Here are some guidelines for sharing your work:
* Choose a `ggplot2`-only example. That means using no visualization packages building on top of `ggplot2` (e.g. `ggmap`, `ggraph`, and more).
* Provide a short explanation for the plot--what is being visualized to tell what story and so on,
* Attach an image file of your plot. You can simply drag & drop the file from your desktop,
* Consider attaching the dataset file if possible to allow others to replicate your work.
    * upload your data file in the CSV format to [this directory](https://github.com/bobaekang/icjia-r-user-group/tree/master/meeting/20190218_ggplot2_example)
    * name the data file as, for example, `bobae_ggplot2_data.csv`
    * *make sure your data has no PII or other privacy-sensitive information*
* Copy/paste the R code you wrote to generate the plot,
    * [use the markdown syntax highlighting for the code block](https://help.github.com/articles/creating-and-highlighting-code-blocks/)
    * include lines that import packages (i.e. `library(ggplot2)`)
    * if you are uploading the data as well, include code to import data from the URL (i.e. `data <- read.csv(DATA_URL)`)
* When possible, try to adopt [the tidyverse style guide](https://style.tidyverse.org/) in writing your R code.

Feel free to leave a comment asking for more clarifications about this exercise. I will also be sharing my own example shortly--you may consider it as a template for sharing yours 😄

**Comment by justinilla** [comment]
## Plot
![justins_ggplot2_participation_map](https://user-images.githubusercontent.com/18745004/52507986-c0cabe00-2bb8-11e9-8248-cff8ae23f9b3.png)

## Description (Problem)
I wanted to create a simple map to show which regions of Illinois participated in a recent survey we conducted. My map used my actual data and was just slightly different than the one you see above. However, the code here will allow you to straight copy-paste it into your R console and re-create exactly what you see. This example borrows spatial data from the ```??mapdata``` package but only uses ``` ggplot2``` to actually create the map layers. I apologize if the ```#commenting``` appears out of hand, but I wanted to help explain what each part of the code is doing, and importantly, why I wanted to do that. My hope is that you will eventually be able to work off of this to add your own data at a later point. 

Note: I followed a [very helpful tutorial](http://eriqande.github.io/rep-res-web/lectures/making-maps-with-R.html) to get me going initially and then riffed off of that using the R-Studio cheat sheets for ggplot2 and many google searches. I would love to get to [this level](https://timogrossenbacher.ch/2016/12/beautiful-thematic-maps-with-ggplot2-only/#final-map) eventually!

## Solution (R Code)

```r 
#1.loads and/or installs and loads necessary packages if they don't exist
packages <- c("ggplot2","devtools","dplyr","stringr", "mapdata")
package.check <- lapply(packages, FUN = function(x) {
  if (!require(x, character.only = TRUE)) {
    install.packages(x, dependencies = TRUE)
    library(x, character.only = TRUE)
  }
})

#2.pull in county outlines and names for Il into dataframes
il_counties <- map_data("county", region = "Illinois")
countynames <- aggregate(cbind(long, lat) ~ subregion, data=il_counties, 
                        FUN=function(x)mean(range(x)))
countynames$names <- tools::toTitleCase(countynames$subregion)

#3.plot county outlines and check appearance
il_full <- ggplot(il_counties, (aes(long, lat, group=group))) +
  geom_polygon(fill="Gray", color = "black") + #changing 'color' value changes county outlines
  coord_fixed(1.3) #determines ratio, edit and see how things distort
il_full

#4.see how you can edit a plot by adding a '+' to an existing plot
il_full + theme_void()

#5.i still want a legend later though so I'm going to produce my own theme by customizing 'theme_void()'
theme_none <- theme_void() + theme(legend.position="right")
il_full + theme_none #notice there is still no legend, but only because there is no data 'fill' added yet

#6a.the map drawing dataset used includes county names, but does not include FIPS numbers
#bring in this file to begin add of FIPS numbers
fips <- read.csv("https://raw.githubusercontent.com/bobaekang/icjia-r-user-group/master/meeting/20190218_ggplot2_example/justin_ggplot2_county_info.csv", header = TRUE)
colnames(fips)[colnames(fips)=="County.Name"] <- "subregion"
fips$subregion <- str_to_lower(fips$subregion)

#6b.fixes county names to allow accurate matching on them, stupid spaces!!
fips$subregion <- recode(fips$subregion, "st. clair" = "st clair")
il_counties$subregion <- recode(il_counties$subregion, "la salle" = "lasalle", "dewitt" = "de witt", 
                                "de kalb" = "dekalb", "du page" = "dupage")
#6c.join the FIPS data
il_counties <- left_join(il_counties, fips, by = "subregion")

#7.Import data to be mapped and merge it on FIPS codes (or other GEO fields)
#this is a demonstration file you can use, you have to add FIPS to your data if it does not exist
mydata <- read.csv("https://raw.githubusercontent.com/bobaekang/icjia-r-user-group/master/meeting/20190218_ggplot2_example/justin_ggplot2_data.csv", header = TRUE)
colnames(mydata)[colnames(mydata)=="fips"] <- "FIPS"

#8.choose appropriate type of join; merge variable name should be EXACTLY similar
mydata.county <- left_join(il_counties, mydata, by = "FIPS")

#9.i want to show participation as binary here (yes/no) and the plot legend is variable type sensitive
#change variable "part" (participation) so that it is 'as.factor'
mydata.county$part <- as.factor(mydata.county$part)

#10.fill the map with your data
mydata.county.map <- il_full +
  geom_polygon(data = mydata.county, aes(fill = part), color = "black")
mydata.county.map

#11.customize colors, title, and legend
participation.map <- mydata.county.map +
  scale_fill_brewer(
    palette = "Blues", labels = c("Not Participating", "Participating")
  ) +
  theme_none +
  ggtitle("\nSurvey Participation by County") +
  theme(plot.title = element_text(hjust = 1)) +
  labs(
    fill = "Key\n"
  )
participation.map

#12.add messy labels, and adjust names somehow???
participation.map +
  geom_text(data = countynames, aes(long, lat, label = names), size = 2.5, inherit.aes = F)

**Comment by mwpowers** [comment]
# Forecast plot
I am late to posting but I will post something that I started but didn't finish. It might be a useful example to try to improve on or explain how certain things can be done. I wanted to check how different forecasts will look based on the inclusion of more past data. I queried CHRI data for felony arrests and used the forecast package to do ARIMA modeling to produce the forecast for the next five years. The package has a function auto.arima that tries to fit the data to the an ARIMA model that best fits the data. R has several plotting tools that are designed specifically for forecasts (see autoplot) but I wanted to do this using more traditional ggplot methods to understand how ggplot works.

![powers_felarrestsforecasts](https://user-images.githubusercontent.com/42590511/53030243-106a7e80-3430-11e9-8730-6175a2718d1e.png)

##Code
```
##required packages
library(tidyverse)
library(scales)
library(forecast)
library(ggfortify)



##Get monthly felony arrests
FA <- read.csv("https://raw.githubusercontent.com/bobaekang/icjia-r-user-group/master/meeting/20190218_ggplot2_example/Powers_FelArrests_YYYYMM.csv", fileEncoding="UTF-8-BOM")


##subset this to have a smaller, more recent time series
FA_201007S <- filter(FA,ArrYrMo >='201007')

##turn both into timer series objects
ts_FA <- ts(data=FA$NumFelArrests,start=c(2001,7),frequency=12)
ts_FA2 <- ts(data=FA_201007S$NumFelArrests,start=c(2010,7),frequency=12)

##auto ARIMA model both and produce forecasts for the next five years
##fortify converts the forecast objects into more useable data frames
AA_ts_FA <- auto.arima(ts_FA)
AA_ts_FA2 <- auto.arima(ts_FA2)

FA1 <- forecast::forecast(AA_ts_FA,level=c(95),h=60) 
FA1 <- fortify(FA1,ts.connect=TRUE) %>%
  as_data_frame(.) %>%
  transmute(.,Year_Month = Index, Felony_Arrests=Data,Fitted_1=Fitted,
            Forecast_1=`Point Forecast`, Low95_1 = `Lo 95`, High95_1 = `Hi 95`) 

FA2 <- forecast::forecast(AA_ts_FA2,level=c(95),h=60)
FA2 <- fortify(FA2,ts.connect=TRUE)  %>% 
  as_data_frame() %>%
  transmute(.,Year_Month = Index, Felony_Arrests=Data,Fitted_2=Fitted,
            Forecast_2=`Point Forecast`, Low95_2 = `Lo 95`, High95_2 = `Hi 95`)


##join the two with left join, FA2 will have fewer rows
FA12 <- left_join(FA1,FA2)

##starting plot
ggplot(FA12, (aes(x=Year_Month))) +
  geom_line(aes(y=Felony_Arrests)) +
  geom_line(aes(y=Forecast_1,color='red')) +
  geom_line(aes(y=Forecast_2,color='green')) +
  scale_y_continuous(name="Felony Arrests", breaks=seq(from=5000,to=12000,by=1000))
```

## What else?
I stopped here. I want to make the legend more useful and change the labeling of the horizontal axis. Another option would be to facet 3 plots. The first plot could be this same plot, the second could be just the forecast zoomed in, and a third plot could be something like the time series of the difference of the two forecasts, or some sort of plot (not even necessarily a time series) that shows the difference between the two forecasts.
