### ISSUE TITLE
Census Module

### ISSUE THREAD

**Issue by kgruschow** [ICJIA/r-user-group#37]
Hi!

I pushed/uploaded to github a module for retrieving census and acs data in R.  It presently supports downloading age X gender X ethnicity data for the 2010 census (block level) and 2013, 2014, 2015, 2016, 2017, and 2018 ACS (tract level). It includes defaults so that a single function call will retrieve the most up to date, precise data for all of Illinois, and do post-processing to ensure usable size and have human readable variables.

It's intended to be **useable right now for real work**, however it is also **intended** to be a demonstration of what I would love to see more of: shared module to access and process commonly shared data sources. Such as the census, but also unified crime reporting, common dates of interest, etc.

If you load the module into your script it will provide two main functions:
1. acs_tracts_by_county (counties, year, cutoff, postprocess)
    1. counties: the county FIPS codes, defaults to all illinois counties
    2. year: the year the ACS was released, defaults to 2018
    3. cutoff: all rows with estimate less than or equal to this will be filtered out, defaults to 1.
    4. postprocess: runs recodes for Age, Gender, Race/Ethnicity, TRUE by default. 
2. census_blocks_by_county (counties, year, cutoff, postprocess)
    1. all arguments as above except the year defaults to 2010 (and 2000 seems to be taken offline)

Additionally, there are two sets of lower level functions, used for postprocessing, these are useful if you have postprocessing turned off and want to manually extract Age, Gender, Ethnicity. The B tree is for ACS and P tree is for Census, the vars list entries contain the census definitions for the respective trees. 

Note that while none of the above is likely to change unless someone reports a bug, I will be implementing additional functionality to make it even more accessible and useful, such as labeling and recoding different geographies, and allowing 'aggregating up' to them, e.g. estimate the the population within the chicago police districts, zip codes, etc.

**Comment by bobaekang** [comment]
Thank you @kgruschow for sharing your work. However, your module is not uploaded to this repo yet.

I was confused at first because I could not find your file. So I looked around for your module and found it in a non-`master` branch (i.e., `patch-1`) of [your forked repository](https://github.com/kgruschow/icjia-r-user-group). 

Your file must be placed in the `master` branch of the current repo. Can you make sure that your file is properly uploaded? Let me know if you need help.

**Comment by kgruschow** [comment]
when i upload/create a file it gives the following error:
"You’re creating a file in a project you don’t have write access to. Submitting a change will create the file in a new branch in your fork kgruschow/icjia-r-user-group, so you can send a pull request. "

My impression (from the UI) was that you would potentially be able to merge it in, or alternately I could merge it in when i have write access? in either case I still do not appear to have write access to the project.

**Comment by bobaekang** [comment]
Update: [Merged](https://github.com/ICJIA/r-user-group/pull/38)!

**Comment by bobaekang** [comment]
BTW, I'm interested in trying some refactoring on your module if you're okay, @kgruschow.

I can make the change a pull request instead of a direct push to the repository so that you can take a look at the changes and merge it only if looking good to you.

**Comment by kgruschow** [comment]
fine by me, and yes on the pull request

**Comment by bobaekang** [comment]
Hey, @kgruschow. I started looking into the module script to refactor, and I'd like to ask you a question:

* Do module users really need to have access to all "postprocessing" functions, such as `age_of_p`, `gender_of_b`, etc.? By design, the user simply does not have access to the raw census data objects, which are the expected input for these functions. What do you think of keeping them inside the module by not exporting them?

**Comment by kgruschow** [comment]
well for starters, I use it and I need it that for code compatibility, when I rewrote it and integrated these earlier on for other people. :)

It's good to have them for two use cases:
1. if you are pulling the whole state, that object is large and having 1 column instead of 3 is good.
2. If you are doing resampling/estimation, especially comparing an external dataset, then it arguably can make sense to stick with the census variable until later in the process.

**Comment by bobaekang** [comment]
Thank you for your feedback, @kgruschow. I now see that changing the input for `postprocess` parameter in `load...` functions can give users data in their original shape.

I have one last question before pushing the first refactored version. Part of the refactoring is renaming internal objects and functions to make them follow more conventional naming practices. For instance, I'm renaming `letter_of_p` to `extract_letter_p` and `age_of_p` to `recode_age_p` to name functions as verbs that are more descriptive. However, I have not changed the module API not to introduce breaking changes.

That said, would you be interested in changing the module API as well (names inside the export list)? This is to improve readability for the module users--especially if you think the module has a potential to be used by others.

**Comment by kgruschow** [comment]
I'm fine with renaming, though i think extract_age_of_p() is the  better naming convention vs recode, etc. 

Recode, to me at least, implies more data wrangling/reorganization by the user, versus uncoding/decoding/extracting data based on the government defined scheme, as is the case here. 


(I am unlikely on the same page as tidyverse/hadley, however i think some functions should have prepositional phrases not verbs, if they are effectively doing something that is almost more like an operator, like subsetting/recodes, etc.

an example:

compare(letter_of_p(x),letter_of_b(y))

vs. 

compare(extract_letter_p(x),extract_letter_b(y))


while the latter is 'tidier', the former is easier to read and understand. the compare function is a verb because it "does" something, the letter of p function "is something"
)

**Comment by bobaekang** [comment]
@kgruschow, here are my rationale for the changed names:

First off, using verbs as names for functions (+using descriptive names in general) is not limited to the `tidyverse` ecosystem. It is shared across many programming communities.

**`recode...` functions**: I believe that the new names better captures what these functions are all about. The `case_when` inside all these functions are essentially re-coding, i.e. replacing the original values with more friendly ones (e.g. "G" to "Multiracial" in case of race).

**`extract...` functions**: I don't think the function `letter_of_*` "is something" in itself though it does "return something" based on the given input--in this case, numbers/letters extracted from the original values. With that in mind, your code example can be rewritten as:

```r
pl <- extract_letter_p(x)
bl <- extract_letter_b(y)
compare(pl, bl)
```

Besides, `letter` and `number` seems a tad bit too generic to my eye. Their return values seem to have some substantive import (`letter` seems to be tied to race and `number` to sex & age) but these names provide little information about them, making it difficult to communicate why their return values are used in certain ways.

* * *

That said, I am very thankful that you chose to keep this conversation going. My intention here is certainly _not_ to intervene in your work: rather, it is to showcase an exemplary discussion on writing a quality, maintainable R program.

**Comment by kgruschow** [comment]
fair enough, go for it. I'll just review the push a bit. I think i can be on board with it so long as the names match what the specific functions actually do.
