### ISSUE TITLE
Submit your challenge ideas for SPSS vs R comparison series

### ISSUE THREAD

**Issue by bobaekang** [ICJIA/r-user-group#40]
## Summary

Submit your data wrangling challenge idea for the SPSS vs R comparison series.

## Main

As discussed during the January 2020 User Group meeting, I am creating this Issue post to invite all of you to submit your data wrangling challenge idea for the SPSS vs R comparison series by commenting on this Issue thread.

Thank you in advance for your participation! 🎉 

**Please read carefully the following instructions.**

### Goal

We are trying to build at least three actionable SPSS vs R data wrangling challenges so that we can have at least three meetings as part of the series.

**Please submit your challenge idea by the end of this month** so that we can choose a specific challenge for February's meeting.

### Submission requirements

Your submission for a challenge must involve a specific data wrangling task using one ore more datasets accessible to all User Group members, i.e. publicly available or stored in a network drive everyone has access to.

Please provide in your submission the details on:

* What datasets to use and where to find them
* What the expected output looks like

Please think of data wrangling tasks that can be solved in a reasonable span of time. Recommended is approximately 10 to 30 minutes to complete your solution. (To R folks, this does not mean how long your script takes to execute. Realistically, any task that requires your data wrangling script to run for more than 1 minute would be too much).

We are _not_ asking you to try solution for your challenge idea before submitting it.

### Challenge scope

Please prioritize the following types of tasks:

* Handling duplicates in a dataset
* Aggregating data by groups
* Merging datasets
  * by joining tables on shared variables
  * by adding rows/columns

You can certainly submit a challenge that does not nicely fall under any of the above. Just keep it relevant to data wrangling.

### Challenge format

Each month, the User Group members will work on solutions for a challenge and demonstrate the solutions in the following monthly meeting. I will be personally in charge of figuring out a viable setup for live demo (i.e. local/remote desktop with both SPSS and R installed as well as access to network drive if needed).

While all members are invited to work on their own solutions for all challenges, I will be politely asking individual members to participate in case there are not enough volunteers for each challenge. Each challenge must have at least one member using SPSS and one member using R to work on solutions.

**Comment by bobaekang** [comment]
I'll go first! ☝️

You may use this as a template for writing your comment on your own challenge idea, which 100% can use the same datasets and involve similar data wrangling operations.

## Summary
* **Datasets to use**: all published UCR datasets since 2010 on Index Crime Offenses
* **Expected output**: A single table containing annual total of `person (i.e. violent) and property offenses and arrests per county for 2016 and 2018 (3 years of data)

## Details

### Dataset

UCR dataset on Index Crime offenses are made available for each year on [this page](http://www.isp.state.il.us/crime/ucrhome.cfm) of the Illinois State Police website. Scroll all the way down, and you'll find links to each year's dataset.

There are few things to note:
* "person" crime includes the following:
  * Murder/Homicide (`CH`)
  * Rape/Sexual assault (`Rape`)
  * Robbery (`Rob`)
  * Aggravated battery/assault (`AggBA`)
* "property" crime includes the following:
  * Burglary (`Burg`)
  * Larceny theft (`Theft`)
  * Moto vehicle theft (`MVT`)
  * Arson (`Arson`)
* The UCR dataset for any given year also provide updated estimates for the previous year, indicated by two digits suffixed to each column name (e.g. Theft18 vs Theft17 for theft offense columns).
  * Use the updated estimates when available. 
  * This means you only need two data files: 2017 and 2018 (latest).
* Arrest columns start with "A" (e.g. Theft18 vs Atheft18 for theft columns)
* Each UCR dataset provides county totals on top. Don't be bothered by agency-level counts.
* Beware of missing values. Some counties did not report their numbers for the given years.
  * Since the output values are sum of all counts, just ignore missing counts and treat them as 0.

### Output

Should look something like the following:

year | county | person_offense | person_arrest | property_offense | property_arrest
---: | :--- | ---: | ---: | ---: | ---:
2016 | Adams | 1111| 2222 | 3333 | 4444 | 
2016 | Alexander | 1111| 2222 | 3333 | 4444 | 
... | ... | ... | ... | ... | ... 
2018 | Winnebago | 1111| 2222 | 3333 | 4444 | 
2018 | Woodford | 1111| 2222 | 3333 | 4444 | 

I believe this offers a good exercise on multiple data wrangling tasks we have discussed, such as aggregating data by group and merging multiple tables by adding/appending them.

It also requires us to conduct other common data wrangling tasks such as removing unnecessary rows and columns, creating new columns, renaming existing columns, reordering rows, etc.

### Other comments

Try to minimize your use of other software.

(For instance, if you're using R, you really don't need to use Excel to manually delete unused rows or columns. You don't even have to manually save the dataset files to your hard disk if you know the shape of the original data.)

If the instructions for this challenge are not clear, feel free to ask for more clarifications. 😄

**Comment by hdotto** [comment]
I made a small dataset of fake data including an identifier variable, date variable, and "event" variable indicating whether the case was an arrest or conviction. I want to use this data to potentially work through the issue of creating a variable that counts another variable sequentially. For example, the data would be sorted by identifier and then date, and then the goal would be to count how many previous arrests each person has at each conviction. So the end result would look something like this (the 1 is the identifier):

1   1/1/2020   Arrest           1 
1   1/2/2020   Arrest           2
1   1/3/2020   Conviction    2
1   1/4/2020   Arrest           3
1   1/5/2020   Conviction    3

(The 1 is the identifier)

I think this would be a good exercise because I think it's a little more challenging/less intuitive than identifying duplicate cases, but also very useful when working with criminal justice data and especially CHRI data.
