### ISSUE TITLE
Charts and Plots in R

### ISSUE THREAD

**Issue by justinilla** [ICJIA/r-user-group#9]
Hi All,
I came across this package called "esquisse" for R that claims it allows the creation of charts and plots via a drag and drop approach. Since some people might find this more intuitive than coding in R, I thought I would [**share it here**](https://towardsdatascience.com/tableau-esque-drag-and-drop-gui-visualization-in-r-901ee9f2fe3f). I haven't had time to try it much myself, but it seems like a really helpful package for beginners in R who need to produce visuals quickly. Importantly, I think it is also a good learning tool because it spits out the R code for the visual you create.

**Comment by bobaekang** [comment]
Hey @justinilla, thanks for sharing. It looks great!

I love how the [`esquisse`](https://github.com/dreamRs/esquisse) mixes the best of programmatic and graphic approaches to exploratory data analysis. That is, the process of building a plot a is done using a graphical user interface, but the same process also generates a code that can be used to quickly and correctly replicate the plot later on. Amazing!

**Comment by lgleich3** [comment]
Off of this discussion and our meeting yesterday, I just got an e-mail for a (partially free...free to a certain extent) new DataCamp training on creating interactive R visualizations using plotly.  In case anyone is interested. See [here](https://www.datacamp.com/courses/interactive-data-visualization-with-plotly-in-r?utm_source=customerio&utm_medium=email&utm_campaign=course_5789).
